<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Mobile Number_vfb-19</name>
   <tag></tag>
   <elementGuidId>f709c79b-2be9-4217-ad2a-525ed2377047</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#vfb-19</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='vfb-19']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9029ad68-aec0-4969-9038-7b7810c5cc31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8740bfd7-358e-49d0-8d52-05e0fd479f3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>vfb-19</value>
      <webElementGuid>d7df2c67-3e99-42d3-a4e2-f6e6ef5ce793</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vfb-19</value>
      <webElementGuid>09f51385-1732-4c15-95ce-afe979822751</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vfb-text  vfb-medium   digits </value>
      <webElementGuid>bb6b3e35-c3b1-46d4-a310-9b32f0be121e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vfb-19&quot;)</value>
      <webElementGuid>8a7787e8-0d32-4868-a19f-c5ee59b92e8a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='vfb-19']</value>
      <webElementGuid>c31d1631-bb3d-4712-9998-afc879639405</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='item-vfb-19']/input</value>
      <webElementGuid>ad23ee82-9f82-45a5-bba5-d18383982de0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[8]/input</value>
      <webElementGuid>d7286404-81e5-45fc-9741-20783a4f731d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'vfb-19' and @id = 'vfb-19']</value>
      <webElementGuid>df8a4284-2357-4828-9012-f43c8a2d7f08</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
