<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Mobile Number_vfb-19</name>
   <tag></tag>
   <elementGuidId>14a6e013-cdee-4378-b134-a6bc9012f11f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#vfb-19</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='vfb-19']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5999f251-1539-43ac-a5cb-09160f762722</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4b88bee3-3a8b-4da4-8c16-4da096c446e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>vfb-19</value>
      <webElementGuid>6a72df63-1990-421a-ab02-8a1fec2b02a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vfb-19</value>
      <webElementGuid>9aa47a94-d134-40ff-90fe-48cbb1d591c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vfb-text  vfb-medium   digits </value>
      <webElementGuid>f4669b94-b6d8-46d3-a141-07931b2999eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vfb-19&quot;)</value>
      <webElementGuid>40a8fcc5-9323-4bd1-ba84-6afcde9fc359</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='vfb-19']</value>
      <webElementGuid>d07112e0-6c65-4e2c-b89b-395bdbfc3b4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='item-vfb-19']/input</value>
      <webElementGuid>bca5360b-338a-4f03-a16f-04f0a2008028</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[8]/input</value>
      <webElementGuid>ab1810fc-072d-48f8-8a38-1d3dcf352759</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'vfb-19' and @id = 'vfb-19']</value>
      <webElementGuid>aa8e3312-8772-45c1-8230-d9d7957dc0c9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
