<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Date of Demo_vfb-18</name>
   <tag></tag>
   <elementGuidId>1734dff7-de7a-45e0-8962-f31aa2725db4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#vfb-18</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='vfb-18']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0321a951-78e6-408e-b864-b4693519b0b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f1c31193-e118-4fb7-a88a-c107cfc6817d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>vfb-18</value>
      <webElementGuid>b8b3e4d0-dbc6-4711-bb01-4b0e0429bf6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vfb-18</value>
      <webElementGuid>d1d6bf2d-5409-41dc-b7a2-c8481be1e04c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vfb-text vfb-date-picker vfb-medium hasDatepicker</value>
      <webElementGuid>34f3c0ae-55ce-40aa-9104-4f1fdd677759</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dp-dateformat</name>
      <type>Main</type>
      <value>mm/dd/yy</value>
      <webElementGuid>1cbf4b0f-a7b7-4c6c-b2f2-402b9d841bb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vfb-18&quot;)</value>
      <webElementGuid>370dbcd9-c140-44e2-98c0-6ae74e6d8700</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='vfb-18']</value>
      <webElementGuid>cf50daa8-84ee-41e1-a745-e0d089c2297c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='item-vfb-18']/span/input</value>
      <webElementGuid>6fcc8be5-9249-426e-8095-979b44b2f783</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/span/input</value>
      <webElementGuid>4d41a40f-8861-49e4-86ac-045c2bacea3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'vfb-18' and @id = 'vfb-18']</value>
      <webElementGuid>8e98a156-b8ca-4d8d-866b-c78a86009ec3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
